package com.example.loadinghtml;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.webkit.WebView;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        WebView myWebView = (WebView) findViewById(R.id.webview);
String random = "<section class=\"section section--body section--first\">\n" +
        "<div class=\"section-content\">\n" +
        "<div class=\"section-inner sectionLayout--insetColumn\">\n" +
        "<p id=\"429b\" class=\"graf graf--p graf--hasDropCapModel graf--hasDropCap graf--hasDropCapImage graf-after--figure\">hen she was 80 years old, my grandmother built a new stone wall in her garden. She&rsquo;d constructed many of them during her &ldquo;retirement&rdquo;?&mdash;?years that she also spent raising me, running the local ambulance corps, and landscaping her three woodsy acres in New York&rsquo;s Hudson Valley. The walls were integral to her garden designs.</p>\n" +
        "<p id=\"9f85\" class=\"graf graf--p graf-after--p\">Sporting a terry cloth headband that slowed (but didn&rsquo;t stop) the sweat sluicing down her cheeks, she lifted and placed the recalcitrant mini-boulders?&mdash;?leftovers from ancient retreating glaciers?&mdash;?into harmonious position, like a slow dance. &ldquo;It&rsquo;s a physical and mental puzzle. A great challenge,&rdquo; she said.</p>\n" +
        "<p id=\"4b25\" class=\"graf graf--p graf-after--p\">The hip-high stone construction still stands at her former home. It was not her first wall?&mdash;?but it was her last. When she died at 82, my grandma&rsquo;s thighs were still tough with muscle and her hands calloused from physical labor.</p>\n" +
        "<blockquote id=\"8a29\" class=\"graf graf--pullquote graf-after--p\">Women get their own category for feats of strength: a separate one, often tied into the tasks of caretaking or motherhood.</blockquote>\n" +
        "<p id=\"9ea9\" class=\"graf graf--p graf-after--pullquote\">Growing up with my grandmother from the age of 4, she was my example of strength and womanhood. But popular culture (especially my favorite &rsquo;80s TV shows) and societal consensus around gender &ldquo;roles&rdquo; eventually taught me that whether it was carrying a bag of groceries, or shoveling a snowy driveway, it is custom that a man&rsquo;s help?&mdash;?or even a boy&rsquo;s?&mdash;?should be enlisted. Men are strong, and women lean on that strength.</p>\n" +
        "<p id=\"4fbb\" class=\"graf graf--p graf-after--p\">Women get their own category for feats of strength: a separate one, often tied into the tasks of caretaking or motherhood. Nobody hesitates to ascribe strength to what women go through in childbirth, or marvel at the power of the woman who pushes a car off her crushed child. But flexing our strength outside those strictures renders women somehow weird or deviant?&mdash;?especially when it comes to athletics.</p>\n" +
        "<p id=\"1a0b\" class=\"graf graf--p graf-after--p\">As seen in the cases of athletes like Olympic weight lifter Sarah Robles, British heptathlete Jessica Ennis-Hill, and tennis star Serena Williams, when a woman performs at the top of her game, her femininity is often questioned. &ldquo;As a female athlete, people want to draw out your masculine traits that make you successful?&mdash;?as opposed to your female traits that have made you successful,&rdquo; says Jennifer Pharr Davis, author of&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.penguinrandomhouse.com/books/548048/the-pursuit-of-endurance-by-jennifer-pharr-davis/9780735221901/\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.penguinrandomhouse.com/books/548048/the-pursuit-of-endurance-by-jennifer-pharr-davis/9780735221901/\"><em class=\"markup--em markup--p-em\">The Pursuit of Endurance</em></a>.</p>\n" +
        "<p id=\"9bd0\" class=\"graf graf--p graf-after--p\">Davis describes herself as tall with large calf muscles, and she says people often tell her that it&rsquo;s these &ldquo;manly&rdquo; traits that allowed her to hike the entire 2,200-mile Appalachian Trail in 46 days, 11 hours, and 20 minutes. (She held the record for the fastest known time (FKT) on the trail from 2011 to 2015.) Davis says this masculinization of her achievement bothers her: &ldquo;It&rsquo;s interesting to me that you&rsquo;re taking away who I am to make yourself more comfortable with my accomplishment,&rdquo; she says.</p>\n" +
        "<p id=\"292f\" class=\"graf graf--p graf-after--p graf--trailing\">Men as a class do have areas in which they are generally more physically able than women. In a random group of 100 people, men can lift heavier things with their upper bodies, because&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.physiology.org/doi/full/10.1152/jappl.2000.89.1.81\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.physiology.org/doi/full/10.1152/jappl.2000.89.1.81\">they have more upper-body muscle</a>. Generally, men can run short distances about 10% faster than women due to&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.physiology.org/doi/full/10.1152/advan.00099.2006\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.physiology.org/doi/full/10.1152/advan.00099.2006\">larger hearts, leaner muscles, and some other muscle efficiencies</a>. But there are other areas where women are generally stronger than men, like accuracy, flexibility, and endurance. As more women continue to enter competitive athletics, and as the emerging science on women and strength increases, the definition of strength becomes much more nuanced.</p>\n" +
        "</div>\n" +
        "</div>\n" +
        "</section>\n" +
        "<section class=\"section section--body\">\n" +
        "<div class=\"section-divider\"><hr class=\"section-divider\" /></div>\n" +
        "<div class=\"section-content\">\n" +
        "<div class=\"section-inner sectionLayout--insetColumn\">\n" +
        "<p id=\"f73a\" class=\"graf graf--p graf--hasDropCapModel graf--hasDropCap graf--hasDropCapImage graf--leading\"><span class=\"graf-dropCap\"><span class=\"graf-dropCapText\">A</span></span>ll athletes are improving?&mdash;?that&rsquo;s the nature of setting new records. Because women have been competing for significantly fewer years than men in almost every sport (for instance, women didn&rsquo;t compete in all the same track events as men until the 2008 Olympics), their gains are bigger and faster. The first woman was allowed to run the Boston Marathon in 1971. In the years since then,&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://bjsm.bmj.com/content/39/7/410\" target=\"_blank\" rel=\"noopener\" data-href=\"https://bjsm.bmj.com/content/39/7/410\">women&rsquo;s race times have improved by leaps and bounds</a>, while men&rsquo;s improvements have been more incremental: &ldquo;In 1976, the world record for men was 2:08:34 and for women 2:38:19&hellip; a difference of 18.71%. Since then, the best male performance has dropped just 2.83%, to 2:04:55. Meanwhile, the best female performance has plummeted an astonishing 14.46% to 2:15:25,&rdquo; according to a 2012 paper that looked at the&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://link.springer.com/article/10.2165/00007256-200737040-00003\" target=\"_blank\" rel=\"noopener\" data-href=\"https://link.springer.com/article/10.2165/00007256-200737040-00003\">history of marathon times</a>. These gains were made even though women still haven&rsquo;t reached &ldquo;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.outsideonline.com/1919331/beating-boys\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.outsideonline.com/1919331/beating-boys\">competitive parity</a>&rdquo; with men. That&rsquo;s determined by looking at the top 10 times in almost any competition?&mdash;?the guys will have similar finishing times, whereas there are larger gaps between the top women, indicating a less dense field of competitors. Sandra Hunter, a professor of exercise physiology at Marquette University, has calculated that about 34% of the gap between men and women&rsquo;s race times is down to a disparities between how many more men participate than women.</p>\n" +
        "<p id=\"11f9\" class=\"graf graf--p graf-after--p\">Similar gains can be seen in other sports, like swimming. At the Olympic level, Johnny Weissmuller won two gold medals in the 1928 Olympic Games, one of which was for the 100-meter swim. (He was the first to break the one-minute record for that race at 58.6 seconds.) Any modern-day female competitive swimmer would be able to beat his times handily?&mdash;?and they have for decades.</p>\n" +
        "<p id=\"c9b4\" class=\"graf graf--p graf-after--p graf--trailing\">As more women compete?&mdash;?and women athletes get more experience?&mdash;?they will continue to set new benchmarks. &ldquo;We haven&rsquo;t got anywhere close to maxing out our genetic &shy;capabilities yet,&rdquo; Rebecca Rusch, a world champion mountain biker who competes with men,&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.outsideonline.com/2169856/longer-race-stronger-we-get\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.outsideonline.com/2169856/longer-race-stronger-we-get\">told&nbsp;<em class=\"markup--em markup--p-em\">Outside</em></a>. Women might even outpace men in shorter events: One study suggests that a female sprinter might beat a man&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.nature.com/articles/431525a\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.nature.com/articles/431525a\">by the 2156 Olympics</a>&nbsp;(based on their current trajectory of improvement over time), though others predict that in shorter events, men will always have a small advantage.</p>\n" +
        "</div>\n" +
        "</div>\n" +
        "</section>\n" +
        "<section class=\"section section--body\">\n" +
        "<div class=\"section-divider\">&nbsp;</div>\n" +
        "<div class=\"section-content\">\n" +
        "<div class=\"section-inner sectionLayout--insetColumn\">\n" +
        "<p id=\"140e\" class=\"graf graf--p graf--hasDropCapModel graf--hasDropCap graf--hasDropCapImage graf--leading\"><span class=\"graf-dropCap\"><span class=\"graf-dropCapText\">O</span></span>ne of the biggest challenges impacting women&rsquo;s ability to compete is the lack of scientific information when it comes to female bodies and exercise. Women weren&rsquo;t regularly included in exercise physiology and biomedicine studies until 1993, when President Clinton passed&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://grants.nih.gov/grants/guide/notice-files/not94-100.html\" target=\"_blank\" rel=\"noopener\" data-href=\"https://grants.nih.gov/grants/guide/notice-files/not94-100.html\">a bill</a>&nbsp;that required that women be included in all National Institutes of Health (NIH)-funded Phase 3 trials (although&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.liebertpub.com/doi/abs/10.1089/jwh.2006.15.1123?prevSearch=allfield%3A%28Adherence%2Bto%2BFederal%2BGuidelines%2Bfor%2BReporting%2Bof%2BSex%2B%2Band%2BRace%2FEthnicity%2Bin%2BClinical%2BTrials%29&amp;searchHistoryKey=&amp;\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.liebertpub.com/doi/abs/10.1089/jwh.2006.15.1123?prevSearch=allfield%3A%28Adherence%2Bto%2BFederal%2BGuidelines%2Bfor%2BReporting%2Bof%2BSex%2B%2Band%2BRace%2FEthnicity%2Bin%2BClinical%2BTrials%29&amp;searchHistoryKey=&amp;\">a 2007 analysis showed</a>&nbsp;that many researchers still weren&rsquo;t meeting the requirement.) In 2014 the&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://grants.nih.gov/grants/funding/women_min/women_min.htm\" target=\"_blank\" rel=\"noopener\" data-href=\"https://grants.nih.gov/grants/funding/women_min/women_min.htm\">NIH updated its rules</a>&nbsp;to mandate that female mice had to be included in animal studies, but a recent review shows that test subjects are still only about 20% female.</p>\n" +
        "<p id=\"863f\" class=\"graf graf--p graf-after--p\">There are many excuses for the lack of gender parity in research, says Stacy Sims, a senior research scientist in exercise physiology at the University of Waikato in New Zealand. &ldquo;I&rsquo;ve heard things like, &lsquo;We don&rsquo;t know enough about men; why do we want to study women?&rsquo; Or it&rsquo;s that &lsquo;women are too different&rsquo; or &lsquo;there&rsquo;s not enough funding,&rsquo;&rdquo; says Sims. Menstrual cycles are often blamed for making results too complex but Hunter calls that excuse &ldquo;rubbish.&rdquo; The fact is that many variables are compensated for in exercise physiology studies: &ldquo;There&rsquo;s other characteristics such as stress, prior physical activity, or nutrition which we don&rsquo;t blink about controlling for,&rdquo; says Hunter.</p>\n" +
        "<blockquote id=\"96ad\" class=\"graf graf--pullquote graf--startsWithDoubleQuote graf-after--p\">&ldquo;In humans, men, but not women, self-reported higher levels of stress when tested in a room previously associated with tonic [chronic] pain.&rdquo;</blockquote>\n" +
        "<p id=\"cdc2\" class=\"graf graf--p graf-after--pullquote\">Despite this limited research, what scientists are learning about women&rsquo;s bodies?&mdash;?and strength in general?&mdash;?is compelling. It also is leading them to question how strength is defined.</p>\n" +
        "<p id=\"6011\" class=\"graf graf--p graf-after--p\">Strength is often characterized by an ability to withstand pain?&mdash;?like continuing a race even through intense discomfort. Studies disagree on whether&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2677686/\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2677686/\">women feel pain more or less severely than men</a>&nbsp;since there is a strong cultural element to reporting one&rsquo;s own pain perception. Regardless, data shows that women appear to be less stressed by pain. A recent study of both mice and humans found&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.cell.com/current-biology/fulltext/S0960-9822%2818%2931496-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0960982218314969%3Fshowall%3Dtrue\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.cell.com/current-biology/fulltext/S0960-9822(18)31496-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0960982218314969%3Fshowall%3Dtrue\">males were more sensitized to pain</a>, and remembered it more clearly: &ldquo;In humans, men, but not women, self-reported higher levels of stress when tested in a room previously associated with tonic [chronic] pain,&rdquo; the researchers wrote. This may give women an advantage. Take, for example, the 2018 Boston Marathon. The day of the race it poured rain and temperatures were freezing. But a look at the final figures showed that women were substantially more likely to finish the race than men. The dropout rate for the race was up almost 80% for men from 2017, but among women it was up only about 12%. It was a trend that was present even among elite runners,&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.nytimes.com/2018/04/20/opinion/boston-marathon-women-nurse.html\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.nytimes.com/2018/04/20/opinion/boston-marathon-women-nurse.html\">the&nbsp;<em class=\"markup--em markup--p-em\">New York Times</em>&nbsp;reported</a>.</p>\n" +
        "<figure id=\"2606\" class=\"graf graf--figure graf--layoutOutsetLeft graf-after--p\" data-scroll=\"native\">\n" +
        "<div class=\"aspectRatioPlaceholder is-locked\">\n" +
        "<div class=\"aspectRatioPlaceholder-fill\">&nbsp;</div>\n" +
        "<div class=\"progressiveMedia js-progressiveMedia graf-image is-canvasLoaded\" data-image-id=\"1*7YgujdQNb7NaMnB-7a7RvA.gif\" data-width=\"800\" data-height=\"640\" data-action=\"zoom\" data-action-value=\"1*7YgujdQNb7NaMnB-7a7RvA.gif\" data-scroll=\"native\"><canvas class=\"progressiveMedia-canvas js-progressiveMedia-canvas\" width=\"75\" height=\"60\"></canvas><img class=\"progressiveMedia-image js-progressiveMedia-image\" src=\"https://cdn-images-1.medium.com/max/1200/1*7YgujdQNb7NaMnB-7a7RvA.gif\" alt=\"\" data-src=\"https://cdn-images-1.medium.com/max/1200/1*7YgujdQNb7NaMnB-7a7RvA.gif\" /></div>\n" +
        "</div>\n" +
        "</figure>\n" +
        "<p id=\"3965\" class=\"graf graf--p graf-after--figure\">If discussions of human physical strength used endurance as the yardstick, women would be strongest. Women have already caught up to, or surpassed, men in some sports like long-distance swimming and&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.runnersworld.com/news/a20839075/2-records-and-5-outright-wins-in-an-amazing-weekend-for-women-ultrarunners/\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.runnersworld.com/news/a20839075/2-records-and-5-outright-wins-in-an-amazing-weekend-for-women-ultrarunners/\">ultrarunning, racking up the wins</a>&nbsp;in mixed-gender races (with less support and training than the men). Recently,&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://www.runnersworld.com/news/a25458347/camille-herron-ultrarunning-world-record/\" target=\"_blank\" rel=\"noopener\" data-href=\"https://www.runnersworld.com/news/a25458347/camille-herron-ultrarunning-world-record/\">Camille Herron won 2018&rsquo;s Desert Solstice</a>&nbsp;run, which lasts for 24 hours (she ran 162.9 miles in that time) and Courtney Dauwalter has won 11 mixed-sex ultramarathons, including the Moab 240, a 238-mile race along the Colorado River in Utah. Dauwalter beat the next-fastest competitor there, a man, by 10 hours.</p>\n" +
        "<p id=\"d833\" class=\"graf graf--p graf-after--p\">In fact, plenty of&nbsp;<a class=\"markup--anchor markup--p-anchor\" href=\"https://bjsm.bmj.com/content/39/7/410\" target=\"_blank\" rel=\"noopener\" data-href=\"https://bjsm.bmj.com/content/39/7/410\">research points to the idea</a>&nbsp;that the longer the distance, the better chance a woman has in beating a man, possibly due to a combination of factors like high pain tolerance and less muscle fatigability. There could also be metabolic reasons?&mdash;?some researchers theorize that women burn energy in a way that supports long-dista</p>\n" +
        "<img src=\"https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/198/smiling-face-with-smiling-eyes_1f60a.png\" alt=\"Smiley face\" width=\"42\" height=\"42\" /></div>\n" +
        "</div>\n" +
        "</section>";
        String html = "<p><img src=\"https://www.welcomenepal.com/uploads/destination/pashupatinath-sm-pilgrims.jpeg\" alt=\"Smiley face\" /> <img src=\"https://www.welcomenepal.com/uploads/destination/pashupatinath-sm-pilgrims.jpeg\" alt=\"Smiley face\" /></p>";
       html = random+html;

        // myWebView.loadData(html,"text/html","UTF-8");
        myWebView.loadDataWithBaseURL(null, "<style>img{display: inline;height: auto;max-width: 100%;}</style>" +html, "text/html", "UTF-8", null);
    }
}
